### ISSUE TITLE
Select cells to render

### ISSUE THREAD

**Issue by colorage** [GordonSmith/vscode-ojs#1]
It would be great to have opportunity to hide some appendix cells

**Comment by GordonSmith** [comment]
Agree - I see it as more a function of the runtime renderer rather than the vscode extension itself.

Once I consolidate the following code:  https://raw.githack.com/hpcc-systems/Visualization/master/demos/storyboard/index.html?Five-Minute%20Introduction%20(.omd) you will have the option via simple CSS toggle - see the "debug" button it will show / hides all values except:
* Ones you put in the markdown specifically
* Any `viewof`

(Note:  the above URL may take a few goes to load).

**Comment by GordonSmith** [comment]
@colorage the above support is now released (the consolidation between this project and https://github.com/hpcc-systems/Visualization/tree/master/packages/observable-md 

If you look at the generated code you will now see an option to `.showValues(true)` - setting that to `false` will hide all the cells which are not a "viewof".  If you do want to display a named value, you will need to explicitly add it to the markdown with the `${myVal}` syntax
