### ISSUE TITLE
Clarify OJS settings and review Preview errors

### ISSUE THREAD

**Issue by RandomFractals** [GordonSmith/vscode-ojs#28]
I noticed that you have a setting to show runtime values: https://github.com/GordonSmith/vscode-ojs#settings

I created standard `.vscode/settings.json` in my OJS notebooks project workspace.

Questions:

1. Does that setting show cell runtime values for the cells that are not markup or viewof?
2. Should I see them in a notebook, in vscode debug console, or dev tools?
3. Should I set that setting in your custom config file per error below?

Please review other errors.

![image](https://user-images.githubusercontent.com/656833/123515824-aea12b80-d65e-11eb-95d9-1a234dc4cf27.png)

Thanks!

**Comment by GordonSmith** [comment]
1+2 - It doesn't work that well in VS Code but should display all the runtime values in the "Problems" tab as "Info".  You can see what it looks like in the web version here:  https://raw.githack.com/hpcc-systems/Visualization/trunk/demos/storyboard/index.html?Five-Minute%20Introduction%20(.omd) (also turning on off the debug option will show the cell values inline).
![image](https://user-images.githubusercontent.com/966863/123536471-64817e00-d722-11eb-8ad2-4be74f64d051.png)
3.  The ojs config file is simply missing from the package and as it happens has already been fixed in master (its part of the ojs syntax highlighting)
I don't think the Buffer error is mine?

**Comment by RandomFractals** [comment]
great. that's for those clarifications. 

yeah, I am not sure why I get that buffer error. it's def. not yours.

btw, I really like that filled cell promises table view. I will double check if it shows up in vscode as you describe. Maybe expand on it a bit in your setting doc section.

**Comment by RandomFractals** [comment]
@GordonSmith not sure if this is still relevant after your recent updates and addition of new OJS notebook kernel.

Feel free to close it, and many thanks for enabling Observable notebooks running in VSCode IDE with this excellent extension!
